# Generated by Django 5.2.6 on 2026-04-06 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("suivi_demande", "0015_add_refuse_statut_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatistiquesDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("JOUR", "Journalier"),
                            ("SEMAINE", "Hebdomadaire"),
                            ("MOIS", "Mensuel"),
                            ("ANNEE", "Annuel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_dossiers", models.IntegerField(default=0)),
                ("dossiers_en_cours", models.IntegerField(default=0)),
                ("dossiers_approuves", models.IntegerField(default=0)),
                ("dossiers_rejetes", models.IntegerField(default=0)),
                ("dossiers_archives", models.IntegerField(default=0)),
                (
                    "montant_total_demande",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_total_approuve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "montant_moyen_demande",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("delai_moyen_traitement", models.FloatField(default=0)),
                ("delai_moyen_analyse", models.FloatField(default=0)),
                ("delai_moyen_validation", models.FloatField(default=0)),
                ("taux_approbation", models.FloatField(default=0)),
                ("taux_rejet", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Statistique Dossier",
                "verbose_name_plural": "Statistiques Dossiers",
                "ordering": ["-date_calcul"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceActeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode_debut", models.DateField()),
                ("periode_fin", models.DateField()),
                ("dossiers_traites", models.IntegerField(default=0)),
                ("dossiers_approuves", models.IntegerField(default=0)),
                ("dossiers_rejetes", models.IntegerField(default=0)),
                ("delai_moyen_traitement", models.FloatField(default=0)),
                ("taux_approbation", models.FloatField(default=0)),
                ("score_performance", models.FloatField(default=0)),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Acteur",
                "verbose_name_plural": "Performances Acteurs",
                "ordering": ["-date_calcul"],
            },
        ),
        migrations.CreateModel(
            name="PredictionRisque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_risque",
                    models.FloatField(
                        help_text="Score de 0 (faible risque) e\xa0 100 (risque eleve)"
                    ),
                ),
                (
                    "probabilite_defaut",
                    models.FloatField(
                        help_text="Probabilite de defaut de paiement (0-1)"
                    ),
                ),
                (
                    "classe_risque",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Risque Faible"),
                            ("MOYEN", "Risque Moyen"),
                            ("ELEVE", "Risque e‰leve"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "facteurs_risque",
                    models.JSONField(
                        default=dict, help_text="Facteurs contribuant au risque"
                    ),
                ),
                ("recommandation", models.TextField(blank=True)),
                ("modele_version", models.CharField(default="v1.0", max_length=50)),
                ("date_prediction", models.DateTimeField(auto_now_add=True)),
                (
                    "confiance",
                    models.FloatField(
                        default=0,
                        help_text="Niveau de confiance de la prediction (0-1)",
                    ),
                ),
                (
                    "dossier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="suivi_demande.dossiercredit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction Risque",
                "verbose_name_plural": "Predictions Risques",
                "ordering": ["-date_prediction"],
            },
        ),
    ]
