# Generated by Django 5.2.6 on 2025-10-02 17:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import suivi_demande.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('produit', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut_agent', models.CharField(choices=[('NOUVEAU', 'Nouveau dossier credit'), ('TRANSMIS_RESP_GEST', 'Transmis au responsable Gestionnaire'), ('TRANSMIS_ANALYSTE', 'Transmis e  l'analyste credit'), ('EN_COURS_ANALYSE', 'En cours d'analyse risque'), ('EN_COURS_VALIDATION_GGR', 'En cours validation GGR'), ('EN_ATTENTE_DECISION_DG', 'En attente decision DG'), ('APPROUVE_ATTENTE_FONDS', 'Approuve, en attente de liberation de fonds'), ('FONDS_LIBERE', 'Fonds libere'), ('REFUSE', 'Refuse / Non approuve')], default='NOUVEAU', max_length=40)),
                ('statut_client', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS_TRAITEMENT', 'En cours de traitement'), ('TERMINE', 'Traitement termine'), ('SE_RAPPROCHER_GEST', 'Se rapprocher du gestionnaire')], default='EN_ATTENTE', max_length=40)),
                ('is_archived', models.BooleanField(default=False)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('acteur_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_en_cours', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('cible_role', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('GESTIONNAIRE', 'Gestionnaire'), ('ANALYSTE', 'Analyste credit'), ('RESPONSABLE_GGR', 'Responsable GGR'), ('BOE', 'Back Office Engagement'), ('SUPER_ADMIN', 'Super administrateur')], max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='suivi_demande.dossiercredit')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Creation du dossier'), ('MISE_A_JOUR', 'Mise e  jour'), ('TRANSITION', "Transition d'etat"), ('RETROU', 'Retour etape precedente'), ('APPROBATION', 'Approbation'), ('REFUS', 'Refus'), ('LIBERATION_FONDS', 'Liberation des fonds')], max_length=30)),
                ('de_statut', models.CharField(blank=True, choices=[('NOUVEAU', 'Nouveau dossier credit'), ('TRANSMIS_RESP_GEST', 'Transmis au responsable Gestionnaire'), ('TRANSMIS_ANALYSTE', 'Transmis e  l'analyste credit'), ('EN_COURS_ANALYSE', 'En cours d'analyse risque'), ('EN_COURS_VALIDATION_GGR', 'En cours validation GGR'), ('EN_ATTENTE_DECISION_DG', 'En attente decision DG'), ('APPROUVE_ATTENTE_FONDS', 'Approuve, en attente de liberation de fonds'), ('FONDS_LIBERE', 'Fonds libere'), ('REFUSE', 'Refuse / Non approuve')], max_length=40, null=True)),
                ('vers_statut', models.CharField(blank=True, choices=[('NOUVEAU', 'Nouveau dossier credit'), ('TRANSMIS_RESP_GEST', 'Transmis au responsable Gestionnaire'), ('TRANSMIS_ANALYSTE', 'Transmis e  l'analyste credit'), ('EN_COURS_ANALYSE', 'En cours d'analyse risque'), ('EN_COURS_VALIDATION_GGR', 'En cours validation GGR'), ('EN_ATTENTE_DECISION_DG', 'En attente decision DG'), ('APPROUVE_ATTENTE_FONDS', 'Approuve, en attente de liberation de fonds'), ('FONDS_LIBERE', 'Fonds libere'), ('REFUSE', 'Refuse / Non approuve')], max_length=40, null=True)),
                ('commentaire_systeme', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='suivi_demande.dossiercredit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('INTERNE', 'Interne'), ('EMAIL', 'Email')], default='INTERNE', max_length=20)),
                ('utilisateur_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=suivi_demande.models.piece_upload_to)),
                ('type_piece', models.CharField(choices=[('CNI', "Carte Nationale d'Identite"), ('FICHE_PAIE', 'Fiche de paie'), ('RELEVE_BANCAIRE', 'Releve bancaire'), ('AUTRE', 'Autre')], max_length=30)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='suivi_demande.dossiercredit')),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('GESTIONNAIRE', 'Gestionnaire'), ('ANALYSTE', 'Analyste credit'), ('RESPONSABLE_GGR', 'Responsable GGR'), ('BOE', 'Back Office Engagement'), ('SUPER_ADMIN', 'Super administrateur')], default='CLIENT', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
