# Generated by Django 5.2.6 on 2025-10-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0003_canevasproposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.IntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_echeance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Paye'), ('EN_RETARD', 'En retard'), ('PAYE_EN_RETARD', 'Paye en retard')], default='EN_ATTENTE', max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='suivi_demande.dossiercredit')),
            ],
            options={
                'verbose_name': 'e‰cheance de paiement',
                'verbose_name_plural': 'e‰cheances de paiement',
                'ordering': ['numero_echeance'],
            },
        ),
    ]
