# Generated by Django 5.2.6 on 2025-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0004_echeancierpaiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaction',
            name='action',
            field=models.CharField(choices=[('CREATION', 'CrÃ©ation du dossier'), ('MISE_A_JOUR', 'Mise Ã  jour'), ('TRANSITION', "Transition d'Ã©tat"), ('RETOUR_CLIENT', 'Retour au client'), ('RETOUR_GESTIONNAIRE', 'Retour au gestionnaire'), ('APPROBATION', 'Approbation'), ('REFUS', 'Refus'), ('LIBERATION_FONDS', 'LibÃ©ration des fonds')], max_length=30),
        ),
    ]
