# Generated by Django 5.2.6 on 2025-11-04 09:20

from django.db import migrations, models
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0005_alter_journalaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='canevasproposition',
            name='logement_autres_precision',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='telephone_domicile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='telephone_travail',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dossiercredit',
            name='consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiercredit',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiercredit',
            name='wizard_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiercredit',
            name='wizard_current_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'e‰tape 1'), (2, 'e‰tape 2'), (3, 'e‰tape 3'), (4, 'e‰tape 4')], default=1),
        ),
        migrations.AlterField(
            model_name='canevasproposition',
            name='regime_matrimonial',
            field=models.CharField(blank=True, choices=[('COMMUNAUTE', 'Communaute des biens'), ('SEPARATION', 'Separation des biens'), ('PARTICIPATION', 'Participation aux acquets'), ('AUTRE', 'Autres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='canevasproposition',
            name='statut_emploi',
            field=models.CharField(choices=[('PRIVE', 'Prive'), ('PUBLIC', 'Public')], default='PRIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='canevasproposition',
            name='statut_logement',
            field=models.CharField(blank=True, choices=[('LOCATAIRE', 'Locataire'), ('PROPRIETAIRE', 'Proprietaire'), ('AUTRES', 'Autres (e  preciser)')], max_length=100),
        ),
        SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='EcheancierPaiement',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "suivi_demande_echeancierpaiement";',
                    reverse_sql=''
                ),
            ],
        ),
    ]
