# Generated by Django 5.2.6 on 2025-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0006_canevasproposition_logement_autres_precision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canevasproposition',
            name='objet_pret',
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='nature_pret',
            field=models.CharField(choices=[('CAUTION', 'Caution'), ('PRET', 'Prêt'), ('DECOUVERT', 'Découvert')], default='PRET', max_length=20),
        ),
    ]
