# Generated by Django 5.2.6 on 2025-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0007_remove_canevasproposition_objet_pret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canevasproposition',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='decision_date_1ere_echeance',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='decision_duree_mois',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='decision_montant_fcfa',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='decision_periodicite',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='decision_taux_pourcent',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='garantie_assurance_vie',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='garantie_autres',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='garantie_billet_ordre',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='garantie_contrat_pret',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='garantie_delegation_salaire',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='garantie_remboursement_anticipe',
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='motif_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
