# Generated by Django 5.2.6 on 2025-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0008_remove_canevasproposition_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canevasproposition',
            name='avis_conseiller_commercial',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='avis_responsable_agence',
        ),
        migrations.RemoveField(
            model_name='canevasproposition',
            name='avis_risque_contrepartie',
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_assurance_deces_invalidite_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_attestation_domiciliation_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_attestation_employeur_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_billet_ordre_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_cni_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_fiche_paie_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='doc_releve_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canevasproposition',
            name='validation_consentement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='type_piece',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('FICHE_PAIE', 'Fiche de paie'), ('RELEVE_BANCAIRE', 'Relevé bancaire'), ('BILLET_ORDRE', 'Billet à ordre'), ('ATTESTATION_EMPLOYEUR', "Attestation de l'employeur"), ('ATTESTATION_DOMICILIATION', 'Attestation de domiciliation irrévocable'), ('ASSURANCE_DECES_INVALIDITE', 'Assurance décès-invalidité'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
