# Generated by Django 5.2.6 on 2025-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0009_remove_canevasproposition_avis_conseiller_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canevasproposition',
            name='proposition_duree_mois',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canevasproposition',
            name='proposition_montant_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='canevasproposition',
            name='proposition_taux_pourcent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
