# Generated by Django 5.2.4 on 2025-11-04 14:47

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0010_alter_canevasproposition_proposition_duree_mois_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiercredit',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Dossier de crédit', 'verbose_name_plural': 'Dossiers de crédit'},
        ),
        migrations.AlterField(
            model_name='dossiercredit',
            name='date_soumission',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dossiercredit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='dossiercredit',
            name='reference',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dossiercredit',
            name='statut_agent',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau dossier crédit'), ('TRANSMIS_RESP_GEST', 'Transmis au responsable Gestionnaire'), ('TRANSMIS_ANALYSTE', 'Transmis à l’analyste crédit'), ('EN_COURS_ANALYSE', 'En cours d’analyse risqué'), ('EN_COURS_VALIDATION_GGR', 'En cours validation GGR'), ('EN_ATTENTE_DECISION_DG', 'En attente décision DG'), ('APPROUVE_ATTENTE_FONDS', 'Approuvé, en attente de libération de fonds'), ('FONDS_LIBERE', 'Fonds libéré'), ('REFUSE', 'Refusé / Non approuvé')], db_index=True, default='NOUVEAU', max_length=40),
        ),
        migrations.AddIndex(
            model_name='dossiercredit',
            index=models.Index(fields=['client', 'statut_agent'], name='suivi_deman_client__456641_idx'),
        ),
        migrations.AddIndex(
            model_name='dossiercredit',
            index=models.Index(fields=['statut_agent', 'is_archived'], name='suivi_deman_statut__ce1604_idx'),
        ),
    ]
