# Generated by Django 5.2.4 on 2025-12-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_demande', '0011_alter_dossiercredit_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditApplication',
        ),
    ]
