# Generated by Django 5.2.6 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_demande", "0012_delete_creditapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canevasproposition",
            name="nature_pret",
            field=models.CharField(
                choices=[
                    ("CAUTION", "Caution"),
                    ("PRÊT", "Prêt"),
                    ("DECOUVERT", "Decouvert"),
                ],
                default="PRÊT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="canevasproposition",
            name="regime_matrimonial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMUNAUTE", "Communauté des biens"),
                    ("SEPARATION", "Séparation des biens"),
                    ("PARTICIPATION", "Participation aux acquêts"),
                    ("AUTRE", "Autres"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="canevasproposition",
            name="situation_famille",
            field=models.CharField(
                choices=[
                    ("CELIBATAIRE", "Célibataire"),
                    ("MARIE", "Marié(e)"),
                    ("DIVORCE", "Divorcé(e)"),
                    ("VEUF", "Veuf/Veuve"),
                ],
                default="MARIE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="canevasproposition",
            name="statut_emploi",
            field=models.CharField(
                choices=[("PRIVE", "Privé"), ("PUBLIC", "Public")],
                default="PRIVE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="canevasproposition",
            name="statut_logement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOCATAIRE", "Locataire"),
                    ("PROPRIETAIRE", "Propriétaire"),
                    ("AUTRES", "Autres (à préciser)"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="dossiercredit",
            name="statut_agent",
            field=models.CharField(
                choices=[
                    ("NOUVEAU", "Nouveau dossier credit"),
                    ("TRANSMIS_RESP_GEST", "Transmis au responsable Gestionnaire"),
                    ("TRANSMIS_ANALYSTE", "Transmis à l'analyste credit"),
                    ("EN_COURS_ANALYSE", "En cours d'analyse risque"),
                    ("EN_COURS_VALIDATION_GGR", "En cours validation GGR"),
                    ("EN_ATTENTE_DECISION_DG", "En attente décision DG"),
                    (
                        "APPROUVE_ATTENTE_FONDS",
                        "Approuvé, en attente de libération de fonds",
                    ),
                    ("FONDS_LIBERE", "Fonds libéré"),
                    ("REFUSE", "Refusé / Non approuvé"),
                ],
                db_index=True,
                default="NOUVEAU",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="dossiercredit",
            name="statut_client",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("EN_COURS_TRAITEMENT", "En cours de traitement"),
                    ("TERMINE", "Traitement terminé"),
                    ("SE_RAPPROCHER_GEST", "Se rapprocher du gestionnaire"),
                ],
                default="EN_ATTENTE",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="dossiercredit",
            name="wizard_current_step",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "étape 1"),
                    (2, "étape 2"),
                    (3, "étape 3"),
                    (4, "étape 4"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="journalaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATION", "Création du dossier"),
                    ("MISE_A_JOUR", "Mise à jour"),
                    ("TRANSITION", "Transition d'état"),
                    ("RETOUR_CLIENT", "Retour au client"),
                    ("RETOUR_GESTIONNAIRE", "Retour au gestionnaire"),
                    ("APPROBATION", "Approbation"),
                    ("REFUS", "Refus"),
                    ("LIBERATION_FONDS", "Libération des fonds"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="journalaction",
            name="de_statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOUVEAU", "Nouveau dossier credit"),
                    ("TRANSMIS_RESP_GEST", "Transmis au responsable Gestionnaire"),
                    ("TRANSMIS_ANALYSTE", "Transmis à l'analyste credit"),
                    ("EN_COURS_ANALYSE", "En cours d'analyse risque"),
                    ("EN_COURS_VALIDATION_GGR", "En cours validation GGR"),
                    ("EN_ATTENTE_DECISION_DG", "En attente décision DG"),
                    (
                        "APPROUVE_ATTENTE_FONDS",
                        "Approuvé, en attente de libération de fonds",
                    ),
                    ("FONDS_LIBERE", "Fonds libéré"),
                    ("REFUSE", "Refusé / Non approuvé"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journalaction",
            name="vers_statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOUVEAU", "Nouveau dossier credit"),
                    ("TRANSMIS_RESP_GEST", "Transmis au responsable Gestionnaire"),
                    ("TRANSMIS_ANALYSTE", "Transmis à l'analyste credit"),
                    ("EN_COURS_ANALYSE", "En cours d'analyse risque"),
                    ("EN_COURS_VALIDATION_GGR", "En cours validation GGR"),
                    ("EN_ATTENTE_DECISION_DG", "En attente décision DG"),
                    (
                        "APPROUVE_ATTENTE_FONDS",
                        "Approuvé, en attente de libération de fonds",
                    ),
                    ("FONDS_LIBERE", "Fonds libéré"),
                    ("REFUSE", "Refusé / Non approuvé"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="piecejointe",
            name="type_piece",
            field=models.CharField(
                choices=[
                    ("CNI", "Carte Nationale d'Identité"),
                    ("FICHE_PAIE", "Fiche de paie"),
                    ("RELEVE_BANCAIRE", "Relevé bancaire"),
                    ("BILLET_ORDRE", "Billet à ordre"),
                    ("ATTESTATION_EMPLOYEUR", "Attestation de l'employeur"),
                    (
                        "ATTESTATION_DOMICILIATION",
                        "Attestation de domiciliation irrevocable",
                    ),
                    ("ASSURANCE_DECES_INVALIDITE", "Assurance deces-invalidité"),
                    ("AUTRE", "Autre"),
                ],
                max_length=30,
            ),
        ),
    ]
