# Generated by Django 5.2.6 on 2026-04-06 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_demande", "0013_alter_canevasproposition_nature_pret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                help_text="Dossier lié à cette notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="suivi_demande.dossiercredit",
            ),
        ),
    ]
