# Generated by Django 5.2.6 on 2026-04-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_demande", "0014_notification_dossier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossiercredit",
            name="statut_client",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("EN_COURS_TRAITEMENT", "En cours de traitement"),
                    ("TERMINE", "Traitement terminé"),
                    ("REFUSE", "Demande refusée"),
                    ("SE_RAPPROCHER_GEST", "Se rapprocher du gestionnaire"),
                ],
                default="EN_ATTENTE",
                max_length=40,
            ),
        ),
    ]
